### ISSUE TITLE
computed optical flow matrix

### ISSUE THREAD

**Issue by shima97** [pacocp/YOLOF#1]
hello, thank you for your code , i have a problem with its computed matrix of optical flow, how can i get that?

**Comment by pacocp** [comment]
Hi,

The computation of the optical flow is performed in line 130:
```
flow = cv.calcOpticalFlowFarneback(prvs, next_, None, 0.5, 2, 15, 3, 5, 1.2, 0)
```

You can return that flow computation without the rest of the computations but you need to change the code then.

Best regads,

Paco

**Comment by shima97** [comment]
Hi,
thank you for your response, would you please tell me how I can give an offline video to this code?? i am new to python :(

**Comment by pacocp** [comment]
You can pass it using the --video-path parameter when executing the script. You need to indicate the path to the video.

**Comment by shima97** [comment]
thank you
